# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OUTPUTS_VIEWER.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 649)
        MainWindow.setStyleSheet("font-family: Nirmala UI;\n"
"background-color: rgb(10, 10, 10);\n"
"color: #dcdcDC;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(40,40,40);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    font: 18px;\n"
"    color: #dcdcDC;\n"
"    background-color: rgba(255,255,255,20);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"color: #dcdcDC;\n"
"   background-color: rgb(40,40,40);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_21 = QtWidgets.QFrame(self.frame_4)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 184))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setMinimumSize(QtCore.QSize(160, 160))
        self.frame_22.setMaximumSize(QtCore.QSize(160, 160))
        self.frame_22.setStyleSheet("QFrame{\n"
"    image: url(:/img/img/settings_10.png);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    border-radius: 80px;\n"
"\n"
"}\n"
"")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_13.addWidget(self.frame_22)
        self.verticalLayout_3.addWidget(self.frame_21)
        self.label_Titulo_Hoja_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Titulo_Hoja_3.setFont(font)
        self.label_Titulo_Hoja_3.setStyleSheet("QLabel{\n"
"    color:  rgb(22,158,206) ;\n"
"    border-bottom: 2px solid  rgb(22,158,206) ;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    padding-bottom: 10px;\n"
"}")
        self.label_Titulo_Hoja_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Titulo_Hoja_3.setObjectName("label_Titulo_Hoja_3")
        self.verticalLayout_3.addWidget(self.label_Titulo_Hoja_3)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 7, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox_port_list = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_port_list.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_port_list.setObjectName("comboBox_port_list")
        self.comboBox_port_list.addItem("")
        self.comboBox_port_list.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_port_list)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_baudrate.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.horizontalLayout_3.addWidget(self.comboBox_baudrate)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.pushButton_connect = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_connect.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(34,36,44);\n"
"    border: none;\n"
"    font: 15px;\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 230), stop:0.512438 rgba(22, 158, 206, 230));\n"
"}")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout_3.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_disconnect.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_disconnect.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(34,36,44);\n"
"    border: none;\n"
"    font: 15px;\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 230), stop:0.512438 rgba(22, 158, 206, 230));\n"
"}")
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout_3.addWidget(self.pushButton_disconnect)
        self.pushButton_refresh = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_refresh.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refresh.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: 2px solid qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    font: 15px;\n"
"    color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    color: white;\n"
"border: none;\n"
"}")
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.verticalLayout_3.addWidget(self.pushButton_refresh)
        self.label_status = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("font-size: 12px;")
        self.label_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_3.addWidget(self.label_status)
        spacerItem = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setMinimumSize(QtCore.QSize(855, 200))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_9.setStyleSheet("QFrame{\n"
"    background-color: rgb(23,23,23);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_Titulo_Hoja_1 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Titulo_Hoja_1.setFont(font)
        self.label_Titulo_Hoja_1.setStyleSheet("QLabel{\n"
"    color:  rgb(22,158,206) ;\n"
"}")
        self.label_Titulo_Hoja_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Titulo_Hoja_1.setObjectName("label_Titulo_Hoja_1")
        self.horizontalLayout_12.addWidget(self.label_Titulo_Hoja_1)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMinimumSize(QtCore.QSize(360, 0))
        self.frame_13.setStyleSheet("QSlider {\n"
"    background: transparent;\n"
"}\n"
"\n"
".QSlider::handle:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    border-radius: 5px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 64))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalSlider_PWM1 = QtWidgets.QSlider(self.frame_15)
        self.horizontalSlider_PWM1.setMinimumSize(QtCore.QSize(180, 0))
        self.horizontalSlider_PWM1.setMaximum(100)
        self.horizontalSlider_PWM1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_PWM1.setObjectName("horizontalSlider_PWM1")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_PWM1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_PWM1_value = QtWidgets.QLabel(self.frame_15)
        self.label_PWM1_value.setObjectName("label_PWM1_value")
        self.horizontalLayout_7.addWidget(self.label_PWM1_value)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 64))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_8 = QtWidgets.QLabel(self.frame_16)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.horizontalSlider_PWM2 = QtWidgets.QSlider(self.frame_16)
        self.horizontalSlider_PWM2.setMinimumSize(QtCore.QSize(180, 0))
        self.horizontalSlider_PWM2.setMaximum(100)
        self.horizontalSlider_PWM2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_PWM2.setObjectName("horizontalSlider_PWM2")
        self.horizontalLayout_8.addWidget(self.horizontalSlider_PWM2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.label_PWM2_value = QtWidgets.QLabel(self.frame_16)
        self.label_PWM2_value.setObjectName("label_PWM2_value")
        self.horizontalLayout_8.addWidget(self.label_PWM2_value)
        self.verticalLayout_6.addWidget(self.frame_16)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setMinimumSize(QtCore.QSize(360, 0))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 64))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.frame_17)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        spacerItem8 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.radioButton_ON1 = QtWidgets.QRadioButton(self.frame_17)
        self.radioButton_ON1.setMinimumSize(QtCore.QSize(70, 40))
        self.radioButton_ON1.setStyleSheet("QRadioButton{\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"    padding-left: 14px;\n"
"    padding-rigth: 10px;\n"
"    background-color: rgb(34,36,44);\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::hover{\n"
"    border: 0px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"    border: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"}\n"
"\n"
"QRadioButton::unchecked {\n"
"    border: 0px;\n"
"    color: rgb(120,120,120);\n"
"background-color: rgb(18, 18, 18);\n"
"}")
        self.radioButton_ON1.setChecked(False)
        self.radioButton_ON1.setObjectName("radioButton_ON1")
        self.horizontalLayout_10.addWidget(self.radioButton_ON1)
        self.radioButton_OFF1 = QtWidgets.QRadioButton(self.frame_17)
        self.radioButton_OFF1.setMinimumSize(QtCore.QSize(70, 40))
        self.radioButton_OFF1.setStyleSheet("QRadioButton{\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 10px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"    padding-left: 11px;\n"
"    padding-rigth: 10px;\n"
"    background-color: rgb(34,36,44);\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::hover{\n"
"    border: 0px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"    border: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"}\n"
"\n"
"QRadioButton::unchecked {\n"
"    border: 0px;\n"
"    color: rgb(120,120,120);\n"
"background-color: rgb(18, 18, 18);\n"
"}")
        self.radioButton_OFF1.setChecked(True)
        self.radioButton_OFF1.setObjectName("radioButton_OFF1")
        self.horizontalLayout_10.addWidget(self.radioButton_OFF1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_7.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 64))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.frame_18)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        spacerItem10 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.radioButton_ON2 = QtWidgets.QRadioButton(self.frame_18)
        self.radioButton_ON2.setMinimumSize(QtCore.QSize(70, 40))
        self.radioButton_ON2.setStyleSheet("QRadioButton{\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"    padding-left: 14px;\n"
"    padding-rigth: 10px;\n"
"    background-color: rgb(34,36,44);\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::hover{\n"
"    border: 0px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"    border: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"}\n"
"\n"
"QRadioButton::unchecked {\n"
"    border: 0px;\n"
"    color: rgb(120,120,120);\n"
"background-color: rgb(18, 18, 18);\n"
"}")
        self.radioButton_ON2.setChecked(False)
        self.radioButton_ON2.setObjectName("radioButton_ON2")
        self.horizontalLayout_11.addWidget(self.radioButton_ON2)
        self.radioButton_OFF2 = QtWidgets.QRadioButton(self.frame_18)
        self.radioButton_OFF2.setMinimumSize(QtCore.QSize(70, 40))
        self.radioButton_OFF2.setStyleSheet("QRadioButton{\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 10px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"    padding-left: 11px;\n"
"    padding-rigth: 10px;\n"
"    background-color: rgb(34,36,44);\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::hover{\n"
"    border: 0px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"    border: 0px;\n"
"    color:  rgb(22,158,206) ;\n"
"}\n"
"\n"
"QRadioButton::unchecked {\n"
"    border: 0px;\n"
"    color: rgb(120,120,120);\n"
"background-color: rgb(18, 18, 18);\n"
"}")
        self.radioButton_OFF2.setChecked(True)
        self.radioButton_OFF2.setObjectName("radioButton_OFF2")
        self.horizontalLayout_11.addWidget(self.radioButton_OFF2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_7.addWidget(self.frame_18)
        self.horizontalLayout_6.addWidget(self.frame_14)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setStyleSheet("\n"
"    background-color: rgb(23,23,23);\n"
"    border-radius: 20px;\n"
"\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setContentsMargins(11, -1, 11, 11)
        self.verticalLayout_8.setSpacing(7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_19 = QtWidgets.QFrame(self.frame_10)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Titulo_Hoja_2 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Titulo_Hoja_2.setFont(font)
        self.label_Titulo_Hoja_2.setStyleSheet("QLabel{\n"
"    color:  rgb(22,158,206) ;\n"
"}")
        self.label_Titulo_Hoja_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Titulo_Hoja_2.setObjectName("label_Titulo_Hoja_2")
        self.horizontalLayout_5.addWidget(self.label_Titulo_Hoja_2)
        self.verticalLayout_8.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_10)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.graph_Layout = QtWidgets.QVBoxLayout()
        self.graph_Layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.graph_Layout.setContentsMargins(10, 0, 10, 10)
        self.graph_Layout.setObjectName("graph_Layout")
        self.horizontalLayout_14.addLayout(self.graph_Layout)
        self.verticalLayout_8.addWidget(self.frame_20)
        self.frame_3 = QtWidgets.QFrame(self.frame_10)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.spinBox_period = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_period.setMinimumSize(QtCore.QSize(80, 40))
        self.spinBox_period.setStyleSheet("QSpinBox{\n"
"    background-color: rgba(255,255,255,20);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #DCDCDC;\n"
"    font-family: Nirmala UI;\n"
"    font: 18px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-arriba-15.png);\n"
"}\n"
"\n"
"QSpinBox::up-button { \n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox::down-button { \n"
"    border: none;\n"
"}")
        self.spinBox_period.setMinimum(10)
        self.spinBox_period.setMaximum(9999)
        self.spinBox_period.setSingleStep(10)
        self.spinBox_period.setObjectName("spinBox_period")
        self.horizontalLayout_9.addWidget(self.spinBox_period)
        self.pushButton_start = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_start.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(34,36,44);\n"
"    border: none;\n"
"    font: 15px;\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 230), stop:0.512438 rgba(22, 158, 206, 230));\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_9.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: 2px solid qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    font: 15px;\n"
"    color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    color: white;\n"
"border: none;\n"
"}")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_9.addWidget(self.pushButton_stop)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("QCheckBox{\n"
"    font-size: 15px;\n"
"    border-radius: 10px;\n"
"    padding-left: 9px;\n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked {\n"
"    border:none;\n"
"    image: url(:/icons/icons/icons8-check-20-dark.png);\n"
"}\n"
"\n"
"QCheckBox::indicator::checked {\n"
"    border:none;\n"
"    image: url(:/icons/icons/icons8-check-20.png);\n"
"}\n"
"\n"
"QCheckBox::unchecked{\n"
"    border: 2px solid rgb(80,80,80);\n"
"    color: rgb(80,80,80);\n"
"}\n"
"\n"
"QCheckBox::checked{\n"
"    color:  white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    border: 2px solid transparent;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_AccX = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_AccX.setMinimumSize(QtCore.QSize(100, 40))
        self.checkBox_AccX.setObjectName("checkBox_AccX")
        self.horizontalLayout_15.addWidget(self.checkBox_AccX)
        self.checkBox_AccY = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_AccY.setMinimumSize(QtCore.QSize(100, 40))
        self.checkBox_AccY.setObjectName("checkBox_AccY")
        self.horizontalLayout_15.addWidget(self.checkBox_AccY)
        self.checkBox_AccZ = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_AccZ.setMinimumSize(QtCore.QSize(100, 40))
        self.checkBox_AccZ.setObjectName("checkBox_AccZ")
        self.horizontalLayout_15.addWidget(self.checkBox_AccZ)
        self.horizontalLayout_9.addWidget(self.frame_5)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.pushButton_clean = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_clean.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_clean.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clean.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(34,36,44);\n"
"    border: none;\n"
"    font: 15px;\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 255), stop:0.512438 rgba(22, 158, 206, 255));\n"
"    \n"
"    image: url(:/icons/icons/icons8-escoba-25.png);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0.507463 rgba(41, 170, 227, 230), stop:0.512438 rgba(22, 158, 206, 230));\n"
"}")
        self.pushButton_clean.setText("")
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.horizontalLayout_9.addWidget(self.pushButton_clean)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_10)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OUTPUTS VIEWER"))
        self.label_Titulo_Hoja_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">SETTINGS</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "PORT NAME:"))
        self.comboBox_port_list.setItemText(0, _translate("MainWindow", "COM12"))
        self.comboBox_port_list.setItemText(1, _translate("MainWindow", "COM9"))
        self.label_4.setText(_translate("MainWindow", "BAUDRATE:"))
        self.pushButton_connect.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "DISCONNECT"))
        self.pushButton_refresh.setText(_translate("MainWindow", "REFRESH PORT LIST"))
        self.label_status.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "Created by <strong>Allione Joaquín</strong>"))
        self.label_Titulo_Hoja_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">CONTROL </span><span style=\" font-size:12pt; font-weight:600;\">OUTPUTS</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "PWM 1"))
        self.label_PWM1_value.setText(_translate("MainWindow", "Value: 100"))
        self.label_8.setText(_translate("MainWindow", "PWM 2"))
        self.label_PWM2_value.setText(_translate("MainWindow", "Value: 100"))
        self.label_12.setText(_translate("MainWindow", "OUTPUT 1"))
        self.radioButton_ON1.setText(_translate("MainWindow", "ON"))
        self.radioButton_OFF1.setText(_translate("MainWindow", "OFF"))
        self.label_13.setText(_translate("MainWindow", "OUTPUT 2"))
        self.radioButton_ON2.setText(_translate("MainWindow", "ON"))
        self.radioButton_OFF2.setText(_translate("MainWindow", "OFF"))
        self.label_Titulo_Hoja_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">ANALOG </span><span style=\" font-size:12pt; font-weight:600;\">INPUT</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Period [mS] :"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.pushButton_stop.setText(_translate("MainWindow", "STOP"))
        self.checkBox_AccX.setText(_translate("MainWindow", "AXIS X"))
        self.checkBox_AccY.setText(_translate("MainWindow", "AXIS Y"))
        self.checkBox_AccZ.setText(_translate("MainWindow", "AXIS Z"))
import resources_rc
